export const especialidades = [
    { "name": "alergia","id":1 },
    { "name": "anatomia patologica","id":2 },
    { "name": "anestesia", "id":3},
    { "name": "angiologia general y hemodinamia", "id":4},
    { "name": "bacteriologia","id":5 },
    { "name": "cardiologia infantil", "id":6},
    { "name": "cardiologia","id":7 },
    { "name": "cirugia plastica y reparadora", "id":8},
    { "name": "cirugia toracica", "id":9},
    { "name": "cirugia de cabeza y cuello","id":10},
    { "name": "cirugia general", "id":11},
    { "name": "cirugia cardiovascular", "id":12},
    { "name": "cirugia vascular periferica", "id":13},
    { "name": "cirugia infantil","id":14 },
    { "name": "clinica medica: medicina interna","id":15 },
    { "name": "dermatologia","id":16},
    { "name": "dermatosifilografia","id":17},
    { "name": "diagnostico por imagenes","id":18},
    { "name": "endocrinologia","id":19},
    { "name": "endoscopia digestiva","id":20},
    { "name": "enfermedades infecciosas: infectología","id":21},
    { "name": "epidemiologia","id":22},
    { "name": "farmacologia","id":23},
    { "name": "fisitria:medicina física y rehabilitación","id":24},
    { "name": "gastroenterologia","id":25},
    { "name": "genetica medica","id":26},
    { "name": "geriatria","id":27},
    { "name": "ginecologia","id":28},
    { "name": "hematologia","id":29},
    { "name": "hemoterapia e inmunohematologia","id":30},
    { "name": "hemoterapia","id":31},
    { "name": "higiene industrial","id":32},
    { "name": "higiene y medicina preventiva","id":33},
    { "name": "inmunologia","id":34},
    { "name": "leprologia","id":35},
    { "name": "mastologia","id":36},
    { "name": "medicina legal","id":37},
    { "name": "medicina nuclear","id":38},
    { "name": "medicina sanitaria","id":39},
    { "name": "medicina del trabajo","id":40},
    { "name": "medicina familiar","id":41},
    { "name": "medicina aeronautica y espacial","id":42},
    { "name": "medicina del deporte","id":43},
    { "name": "nefrologia","id":44},
    { "name": "neonatologia","id":45},
    { "name": "neumonologia","id":46},
    { "name": "neurocirugia","id":47},
    { "name": "neurologia infantil","id":48},
    { "name": "neurologia","id":49},
    { "name": "nutricion","id":50},
    { "name": "obstetricia","id":51},
    { "name": "oftalmologia","id":52},
    { "name": "oncologia (clínica)","id":53},
    { "name": "ortopedia y traumatologia","id":54},
    { "name": "otorrinolaringologia","id":55},
    { "name": "pediatria (clínica pediátrica)","id":56},
    { "name": "proctologia","id":57},
    { "name": "psicologia medica (clínica)","id":58},
    { "name": "psiquiatria","id":59},
    { "name": "psiquiatria infantil","id":60},
    { "name": "quemados","id":61},
    { "name": "radiologia","id":62},
    { "name": "radioterapia (terapia radiante)","id":63},
    { "name": "reumatologia","id":64},
    { "name": "salud publica","id":65},
    { "name": "terapia intensiva","id":66},
    { "name": "tisiologia","id":67},
    { "name": "tisioneumonologia","id":68},
    { "name": "tocoginecologia","id":69},
    { "name": "toxicologia","id":70},
    { "name": "urologia","id":71 }
]