export const obrasSociales = [
    { "name": "Sin Obra Social","id":0 },
    { "name": "S.R.T.","id":1 },
    { "name": "OSSEG ","id":2 },
    { "name": "SWISS MEDICAL S.A.", "id":3},
    { "name": "O.S.E.T.Y A.", "id":4},
    { "name": "OSSACRA","id":5 },
    { "name": "T.V. SALUD", "id":6},
    { "name": "PREVENCION SALUD S.A.","id":7 },
    { "name": "MEDICUS S.A", "id":8},
    { "name": "BRAMED SRL", "id":9},
    { "name": "O.S.P.A","id":10},
    { "name": "ASOCIACION MUTUAL 23 DE DICIEMBRE", "id":11},
    { "name": "O.S.P.E.S (O.S.PERS.EST.SERVICIO)", "id":12},
    { "name": "RED DE SEGURO MEDICO - MOSAISTAS ", "id":13},
    { "name": "JERARQUICOS SALUD", "id":14},
    { "name": "PAMI", "id":15},
    { "name": "NOBIS S.A.", "id":16},
    { "name": "O.S.E.P", "id":17},
    { "name": "UNION PERSONAL", "id":18},
    { "name": "O.S.CONDUCT.CAMIONEROS Y PTAC", "id":19},
    { "name": "O.S.T.P.C.P.H. y A.R.A - PASTELEROS ", "id":20},
    { "name": "O.S.A.M - ITER MEDICINA S.A (OSAM)", "id":21},
    { "name": " O.S.F.A.T.U.N.", "id":22},
    { "name": "O.S.F.A.T.L.Y F.", "id":23},
    { "name": "DI.B.P.F.A.(INCLUYE IOSFA-IOSFE)", "id":24},
    { "name": "PREMEDICA - OSPIT", "id":25},
    { "name": "PREMEDICA S.A. - OSPSIP", "id":26},
    { "name": "PREMEDICA S.A. (PLAN A 100/A 200) ", "id":27},
    { "name": "PREMEDICA S.A. (PLAN A300)", "id":28},
    { "name": "PREMEDICA S.A. - OSSIMRA", "id":29},
    { "name": "PREMEDICA S.A. - OSPEGAP", "id":30},
    { "name": "PREMEDICA S.A. - FEDECAMARAS", "id":31},
    { "name": "UNIMED S.A", "id":32},
    { "name": "PODER JUDICIAL", "id":33},
    { "name": "O.S.A.P.M. ", "id":34},
    { "name": "O.S.M.A.T.A. ", "id":35},
    { "name": "OMINT S.A. DE SERVICIOS", "id":36},
    { "name": "OSPSA - ATSA", "id":37},
    { "name": "R.A.S ", "id":38},
    { "name": "CONFERENCIA EPISCOPAL ARGENTINA", "id":39},
    { "name": "OSPIQyP", "id":40},
    { "name": "SANCOR SALUD", "id":41},
    { "name": "OBRA SOCIAL DE FUTBOLISTAS", "id":42},
    { "name": "O.S.Je.R.A.", "id":43},
    { "name": "BIENESTAR SALUD ", "id":44},
    { "name": "OSPIDA", "id":45},
    { "name": "MEDIFE ", "id":46},
    { "name": "OSDEPYM", "id":47},
    { "name": "GALENO S.A.", "id":48},
    { "name": "CAPITANES Y BAQUEANOS", "id":49},
    { "name": "PREMEDICA S.A. - OSCONARA", "id":50},
    { "name": "O.S.T.R.A.C - SCIS", "id":51},
    { "name": "OSPACA -ITER MEDICINA S.A", "id":52}
   
]